name: example
description: A new internationalized Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_intl:

dependency_overrides:
  json_intl:
    path: ..

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true

  # Add the intl assets
  assets:
    - assets/intl/
