name: json_intl
description: Flutter Internationalization library based on Json files and mustache replacement strings.
homepage: https://github.com/DavBfr/json_intl
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 2.1.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  args: ^2.1.0
  dart_style: ">=1.2.9 <3.0.0"
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.0.0
  meta: ^1.3.0
  path: ^1.8.0
  simple_mustache: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.0

flutter:

executables:
  json_intl:
