name: json_intl
description: Flutter Internationalization library based on Json files
version: 0.0.2
homepage: https://github.com/DavBfr/json_intl
author: David PHAM-VAN <dev.nfet.net@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.0
  dart_style: ^1.2.9
  meta: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_extract: ^1.2.0
  pedantic: ^1.8.0

flutter:

executables:
  json_intl:
