name: json_intl
description: Flutter Internationalization library based on Json files and mustache replacement strings.
homepage: https://github.com/DavBfr/json_intl
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 2.0.0-nullsafety.1

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  args: ^1.5.2
  dart_style: ^1.2.9
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety
  meta: ^1.3.0-nullsafety.6
  path: ^1.8.0-nullsafety.3
  simple_mustache: ^2.0.0-nullsafety

dependency_overrides:
  args:
    git: https://github.com/dart-lang/args

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety

flutter:

executables:
  json_intl:
