name: json_intl
description: Flutter Internationalization library based on Json files and mustache replacement strings.
version: 1.0.0
homepage: https://github.com/DavBfr/json_intl
author: David PHAM-VAN <dev.nfet.net@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_style: ^1.2.9
  intl: ^0.16.0
  logging: ^0.11.0
  meta: ^1.1.0
  args: ^1.6.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_extract: ^1.2.0
  pedantic: ^1.8.0

flutter:

executables:
  json_intl:
