name: example
description: A new internationalized Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_intl:

dependency_overrides:
  json_intl:
    git:
      url: https://github.com/DavBfr/json_intl
      ref: analyzer
      path: json_intl
  json_intl_gen:
    git:
      url: https://github.com/DavBfr/json_intl
      ref: analyzer
      path: json_intl_gen

dev_dependencies:
  build_runner:
  flutter_lints:
  json_intl_gen:

flutter:
  uses-material-design: true
