name: json_intl
description: Flutter Internationalization library based on Json files and mustache replacement strings.
homepage: https://github.com/DavBfr/json_intl
_author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logging: ^1.1.0
  meta: ">=1.3.0 <=2.0.0"
  path: ^1.8.0
  simple_mustache: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ">=1.16.0 <2.0.0"
