name: json_intl_gen
description: Flutter Internationalization library based on Json files and mustache replacement strings. Code generator library.
homepage: https://github.com/DavBfr/json_intl
_author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 3.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  dart_style: ^2.2.4
  json_intl: ^3.0.0
  logging: ^1.0.0
  path: ^1.8.0

_dependency_overrides:
  json_intl:
    path: ../json_intl

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0

executables:
  json_intl_gen:
